language: php

php:
  - 7.0
  - 7.1

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 LEVELDB_VERSION=1.18 SHLIB_DIR=""
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 LEVELDB_VERSION=1.20 SHLIB_DIR="out-shared/"

before_script:
 - sudo apt-get update -qq
 - sudo apt-get install valgrind -qq
 - sh travis/prepare.sh

script: sh travis/run-test.sh

#notifications:
#  email:
#    - reeze.xia@gmail.com
